version: '3.6'

services:

  uzaleo:
    container_name: uzaleo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true